name: UUP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 cabextract wimtools chntpw genisoimage

      - name: Build ISO
        run: |
          unzip uup.zip
          bash uup_download_linux.sh

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SF_SSH_KEY }}" > ssh-key
          chmod 600 ssh-key

      - name: Upload to SourceForge
        run: |
          scp -o StrictHostKeyChecking=no -i ssh-key *.ISO parixshit@frs.sourceforge.net:/home/frs/project/winiso/
