name: UUP

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt update && sudo apt install aria2 cabextract wimtools chntpw genisoimage

      - name: Run a multi-line script
        run: |
          unzip *.zip
          bash uup_download_linux.sh
